
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/mediamonks-clustering-product/streamlit-test/imagen1:$SHORT_SHA', '.']

  
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/mediamonks-clustering-product/streamlit-test/imagen1:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'streamlit-test'
    - '--image'
    - 'us-central1-docker.pkg.dev/mediamonks-clustering-product/streamlit-test/imagen1:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'

images:
- 'us-central1-docker.pkg.dev/mediamonks-clustering-product/streamlit-test/imagen1:$SHORT_SHA'
